/** @param {string} city @param {string} stateOrTerritory */
function us(city, stateOrTerritory) {
  return `${city}, ${stateOrTerritory}, United States`
}

const US_STATE_NAMES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]

const US_STATES = US_STATE_NAMES.map((s) => `${s}, United States`)

/** More cities than we had before — add freely as needed. */
const US_CITIES = [
  // Alabama
  us('Birmingham', 'Alabama'),
  us('Huntsville', 'Alabama'),
  us('Mobile', 'Alabama'),
  us('Montgomery', 'Alabama'),
  // Alaska
  us('Anchorage', 'Alaska'),
  us('Fairbanks', 'Alaska'),
  us('Juneau', 'Alaska'),
  // Arizona
  us('Phoenix', 'Arizona'),
  us('Tucson', 'Arizona'),
  us('Scottsdale', 'Arizona'),
  us('Sedona', 'Arizona'),
  us('Flagstaff', 'Arizona'),
  us('Grand Canyon Village', 'Arizona'),
  // Arkansas
  us('Little Rock', 'Arkansas'),
  us('Hot Springs', 'Arkansas'),
  // California
  us('Los Angeles', 'California'),
  us('San Diego', 'California'),
  us('San Francisco', 'California'),
  us('San Jose', 'California'),
  us('Sacramento', 'California'),
  us('Oakland', 'California'),
  us('Fresno', 'California'),
  us('Long Beach', 'California'),
  us('Santa Barbara', 'California'),
  us('Monterey', 'California'),
  us('Palm Springs', 'California'),
  us('Anaheim', 'California'),
  us('Santa Monica', 'California'),
  us('Malibu', 'California'),
  us('Napa', 'California'),
  us('Sonoma', 'California'),
  us('Big Sur', 'California'),
  us('Lake Tahoe', 'California'),
  us('Yosemite Valley', 'California'),
  // Colorado
  us('Denver', 'Colorado'),
  us('Colorado Springs', 'Colorado'),
  us('Boulder', 'Colorado'),
  us('Aspen', 'Colorado'),
  us('Vail', 'Colorado'),
  us('Breckenridge', 'Colorado'),
  us('Fort Collins', 'Colorado'),
  // Connecticut
  us('Hartford', 'Connecticut'),
  us('New Haven', 'Connecticut'),
  us('Stamford', 'Connecticut'),
  // Delaware
  us('Wilmington', 'Delaware'),
  // Florida
  us('Miami', 'Florida'),
  us('Orlando', 'Florida'),
  us('Tampa', 'Florida'),
  us('Jacksonville', 'Florida'),
  us('Fort Lauderdale', 'Florida'),
  us('Key West', 'Florida'),
  us('St. Augustine', 'Florida'),
  us('Naples', 'Florida'),
  us('Sarasota', 'Florida'),
  us('Panama City Beach', 'Florida'),
  us('Daytona Beach', 'Florida'),
  // Georgia
  us('Atlanta', 'Georgia'),
  us('Savannah', 'Georgia'),
  us('Athens', 'Georgia'),
  us('Augusta', 'Georgia'),
  // Hawaii
  us('Honolulu', 'Hawaii'),
  us('Maui', 'Hawaii'),
  us('Kauai', 'Hawaii'),
  us('Kailua-Kona', 'Hawaii'),
  // Idaho
  us('Boise', 'Idaho'),
  us('Sun Valley', 'Idaho'),
  // Illinois
  us('Chicago', 'Illinois'),
  us('Springfield', 'Illinois'),
  us('Galena', 'Illinois'),
  // Indiana
  us('Indianapolis', 'Indiana'),
  us('Bloomington', 'Indiana'),
  us('South Bend', 'Indiana'),
  // Iowa
  us('Des Moines', 'Iowa'),
  us('Iowa City', 'Iowa'),
  // Kansas
  us('Kansas City', 'Kansas'),
  us('Wichita', 'Kansas'),
  // Kentucky
  us('Louisville', 'Kentucky'),
  us('Lexington', 'Kentucky'),
  // Louisiana
  us('New Orleans', 'Louisiana'),
  us('Baton Rouge', 'Louisiana'),
  us('Lafayette', 'Louisiana'),
  // Maine
  us('Portland', 'Maine'),
  us('Bar Harbor', 'Maine'),
  // Maryland
  us('Baltimore', 'Maryland'),
  us('Annapolis', 'Maryland'),
  // Massachusetts
  us('Boston', 'Massachusetts'),
  us('Cambridge', 'Massachusetts'),
  us('Cape Cod', 'Massachusetts'),
  us('Nantucket', 'Massachusetts'),
  us('Martha\'s Vineyard', 'Massachusetts'),
  us('Salem', 'Massachusetts'),
  // Michigan
  us('Detroit', 'Michigan'),
  us('Grand Rapids', 'Michigan'),
  us('Traverse City', 'Michigan'),
  us('Ann Arbor', 'Michigan'),
  us('Mackinac Island', 'Michigan'),
  // Minnesota
  us('Minneapolis', 'Minnesota'),
  us('Saint Paul', 'Minnesota'),
  us('Duluth', 'Minnesota'),
  // Mississippi
  us('Jackson', 'Mississippi'),
  us('Biloxi', 'Mississippi'),
  // Missouri
  us('Kansas City', 'Missouri'),
  us('St. Louis', 'Missouri'),
  us('Branson', 'Missouri'),
  // Montana
  us('Billings', 'Montana'),
  us('Bozeman', 'Montana'),
  us('Glacier National Park', 'Montana'),
  // Nebraska
  us('Omaha', 'Nebraska'),
  // Nevada
  us('Las Vegas', 'Nevada'),
  us('Reno', 'Nevada'),
  us('Lake Tahoe', 'Nevada'),
  // New Hampshire
  us('Manchester', 'New Hampshire'),
  us('Portsmouth', 'New Hampshire'),
  // New Jersey
  us('Newark', 'New Jersey'),
  us('Jersey City', 'New Jersey'),
  us('Atlantic City', 'New Jersey'),
  us('Cape May', 'New Jersey'),
  // New Mexico
  us('Albuquerque', 'New Mexico'),
  us('Santa Fe', 'New Mexico'),
  us('Taos', 'New Mexico'),
  // New York
  us('New York', 'New York'),
  us('Buffalo', 'New York'),
  us('Rochester', 'New York'),
  us('Albany', 'New York'),
  us('The Hamptons', 'New York'),
  us('Lake Placid', 'New York'),
  // North Carolina
  us('Charlotte', 'North Carolina'),
  us('Raleigh', 'North Carolina'),
  us('Asheville', 'North Carolina'),
  us('Wilmington', 'North Carolina'),
  us('Outer Banks', 'North Carolina'),
  // North Dakota
  us('Fargo', 'North Dakota'),
  // Ohio
  us('Columbus', 'Ohio'),
  us('Cleveland', 'Ohio'),
  us('Cincinnati', 'Ohio'),
  // Oklahoma
  us('Oklahoma City', 'Oklahoma'),
  us('Tulsa', 'Oklahoma'),
  // Oregon
  us('Portland', 'Oregon'),
  us('Eugene', 'Oregon'),
  us('Bend', 'Oregon'),
  // Pennsylvania
  us('Philadelphia', 'Pennsylvania'),
  us('Pittsburgh', 'Pennsylvania'),
  us('Hershey', 'Pennsylvania'),
  us('Gettysburg', 'Pennsylvania'),
  // Rhode Island
  us('Providence', 'Rhode Island'),
  us('Newport', 'Rhode Island'),
  // South Carolina
  us('Charleston', 'South Carolina'),
  us('Myrtle Beach', 'South Carolina'),
  us('Hilton Head Island', 'South Carolina'),
  us('Greenville', 'South Carolina'),
  // South Dakota
  us('Sioux Falls', 'South Dakota'),
  us('Rapid City', 'South Dakota'),
  us('Deadwood', 'South Dakota'),
  // Tennessee
  us('Nashville', 'Tennessee'),
  us('Memphis', 'Tennessee'),
  us('Knoxville', 'Tennessee'),
  us('Gatlinburg', 'Tennessee'),
  // Texas
  us('Houston', 'Texas'),
  us('Dallas', 'Texas'),
  us('Austin', 'Texas'),
  us('San Antonio', 'Texas'),
  us('Fort Worth', 'Texas'),
  us('El Paso', 'Texas'),
  us('Galveston', 'Texas'),
  us('Corpus Christi', 'Texas'),
  us('Marfa', 'Texas'),
  // Utah
  us('Salt Lake City', 'Utah'),
  us('Park City', 'Utah'),
  us('Moab', 'Utah'),
  us('Zion National Park', 'Utah'),
  // Vermont
  us('Burlington', 'Vermont'),
  us('Stowe', 'Vermont'),
  // Virginia
  us('Richmond', 'Virginia'),
  us('Virginia Beach', 'Virginia'),
  us('Williamsburg', 'Virginia'),
  us('Charlottesville', 'Virginia'),
  us('Alexandria', 'Virginia'),
  // Washington
  us('Seattle', 'Washington'),
  us('Tacoma', 'Washington'),
  us('Spokane', 'Washington'),
  us('Olympic National Park', 'Washington'),
  // West Virginia
  us('Charleston', 'West Virginia'),
  us('Harpers Ferry', 'West Virginia'),
  // Wisconsin
  us('Milwaukee', 'Wisconsin'),
  us('Madison', 'Wisconsin'),
  us('Door County', 'Wisconsin'),
  // Wyoming
  us('Jackson', 'Wyoming'),
  us('Cody', 'Wyoming'),
  us('Yellowstone National Park', 'Wyoming'),
  // Territories & DC
  us('Washington', 'District of Columbia'),
  us('San Juan', 'Puerto Rico'),
  us('Ponce', 'Puerto Rico'),
  us('Charlotte Amalie', 'U.S. Virgin Islands'),
  us('Hagåtña', 'Guam'),
]

const INTERNATIONAL = [
  // Canada
  'Toronto, Ontario, Canada',
  'Vancouver, British Columbia, Canada',
  'Montreal, Quebec, Canada',
  'Calgary, Alberta, Canada',
  'Edmonton, Alberta, Canada',
  'Ottawa, Ontario, Canada',
  'Quebec City, Quebec, Canada',
  'Victoria, British Columbia, Canada',
  'Banff, Alberta, Canada',
  'Whistler, British Columbia, Canada',
  'Niagara Falls, Ontario, Canada',
  'Halifax, Nova Scotia, Canada',
  // Mexico & Caribbean
  'Mexico City, Mexico',
  'Cancún, Mexico',
  'Playa del Carmen, Mexico',
  'Tulum, Mexico',
  'Puerto Vallarta, Mexico',
  'Cabo San Lucas, Mexico',
  'Oaxaca, Mexico',
  'San Miguel de Allende, Mexico',
  'Guadalajara, Mexico',
  'San José del Cabo, Mexico',
  'Nassau, Bahamas',
  'Montego Bay, Jamaica',
  'Kingston, Jamaica',
  'Punta Cana, Dominican Republic',
  'San Juan, Puerto Rico',
  'Havana, Cuba',
  'Varadero, Cuba',
  'Bridgetown, Barbados',
  'Aruba, Aruba',
  'Curaçao, Curaçao',
  'Saint Thomas, U.S. Virgin Islands',
  'Providenciales, Turks and Caicos',
  // Central & South America
  'Panama City, Panama',
  'San José, Costa Rica',
  'La Fortuna, Costa Rica',
  'Antigua Guatemala, Guatemala',
  'Roatán, Honduras',
  'Belize City, Belize',
  'Ambergris Caye, Belize',
  'Lima, Peru',
  'Cusco, Peru',
  'Machu Picchu, Peru',
  'Bogotá, Colombia',
  'Medellín, Colombia',
  'Cartagena, Colombia',
  'Quito, Ecuador',
  'Galápagos Islands, Ecuador',
  'La Paz, Bolivia',
  'Santiago, Chile',
  'Valparaíso, Chile',
  'Patagonia, Chile',
  'Buenos Aires, Argentina',
  'Mendoza, Argentina',
  'Bariloche, Argentina',
  'Rio de Janeiro, Brazil',
  'São Paulo, Brazil',
  'Salvador, Brazil',
  'Florianópolis, Brazil',
  'Iguazu Falls, Brazil',
  // Europe — Western
  'London, United Kingdom',
  'Edinburgh, United Kingdom',
  'Manchester, United Kingdom',
  'Liverpool, United Kingdom',
  'Dublin, Ireland',
  'Galway, Ireland',
  'Paris, France',
  'Lyon, France',
  'Nice, France',
  'Bordeaux, France',
  'Strasbourg, France',
  'Marseille, France',
  'Amsterdam, Netherlands',
  'Rotterdam, Netherlands',
  'Brussels, Belgium',
  'Bruges, Belgium',
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Frankfurt, Germany',
  'Cologne, Germany',
  'Vienna, Austria',
  'Salzburg, Austria',
  'Zurich, Switzerland',
  'Geneva, Switzerland',
  'Lucerne, Switzerland',
  'Interlaken, Switzerland',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Seville, Spain',
  'Valencia, Spain',
  'Granada, Spain',
  'Ibiza, Spain',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Faro, Portugal',
  'Madeira, Portugal',
  'Azores, Portugal',
  'Rome, Italy',
  'Milan, Italy',
  'Florence, Italy',
  'Venice, Italy',
  'Naples, Italy',
  'Amalfi Coast, Italy',
  'Cinque Terre, Italy',
  'Sicily, Italy',
  'Sardinia, Italy',
  // Northern / Eastern Europe
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Bergen, Norway',
  'Helsinki, Finland',
  'Reykjavík, Iceland',
  'Warsaw, Poland',
  'Kraków, Poland',
  'Prague, Czech Republic',
  'Český Krumlov, Czech Republic',
  'Budapest, Hungary',
  'Ljubljana, Slovenia',
  'Dubrovnik, Croatia',
  'Split, Croatia',
  'Athens, Greece',
  'Santorini, Greece',
  'Mykonos, Greece',
  'Crete, Greece',
  'Bucharest, Romania',
  'Sofia, Bulgaria',
  'Belgrade, Serbia',
  // UK & Ireland extras
  'Belfast, United Kingdom',
  'Cardiff, United Kingdom',
  'Bath, United Kingdom',
  // Mediterranean & Turkey
  'Istanbul, Turkey',
  'Cappadocia, Turkey',
  'Antalya, Turkey',
  'Malta, Malta',
  'Valletta, Malta',
  // Middle East
  'Dubai, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Doha, Qatar',
  'Tel Aviv, Israel',
  'Jerusalem, Israel',
  'Petra, Jordan',
  'Amman, Jordan',
  'Muscat, Oman',
  'Riyadh, Saudi Arabia',
  // Africa
  'Cairo, Egypt',
  'Luxor, Egypt',
  'Marrakech, Morocco',
  'Fez, Morocco',
  'Casablanca, Morocco',
  'Chefchaouen, Morocco',
  'Cape Town, South Africa',
  'Johannesburg, South Africa',
  'Maasai Mara, Kenya',
  'Nairobi, Kenya',
  'Zanzibar, Tanzania',
  'Serengeti, Tanzania',
  'Victoria Falls, Zimbabwe',
  'Mauritius, Mauritius',
  'Seychelles, Seychelles',
  // South Asia
  'Mumbai, India',
  'Delhi, India',
  'Jaipur, India',
  'Goa, India',
  'Kerala, India',
  'Udaipur, India',
  'Agra, India',
  'Kathmandu, Nepal',
  'Colombo, Sri Lanka',
  'Maldives, Maldives',
  // East & Southeast Asia
  'Tokyo, Japan',
  'Kyoto, Japan',
  'Osaka, Japan',
  'Hiroshima, Japan',
  'Okinawa, Japan',
  'Sapporo, Japan',
  'Seoul, South Korea',
  'Busan, South Korea',
  'Taipei, Taiwan',
  'Hong Kong, Hong Kong',
  'Macau, Macau',
  'Shanghai, China',
  'Beijing, China',
  'Xi\'an, China',
  'Chengdu, China',
  'Guilin, China',
  'Bangkok, Thailand',
  'Chiang Mai, Thailand',
  'Phuket, Thailand',
  'Koh Samui, Thailand',
  'Hanoi, Vietnam',
  'Ho Chi Minh City, Vietnam',
  'Hoi An, Vietnam',
  'Halong Bay, Vietnam',
  'Singapore, Singapore',
  'Kuala Lumpur, Malaysia',
  'Penang, Malaysia',
  'Langkawi, Malaysia',
  'Jakarta, Indonesia',
  'Bali, Indonesia',
  'Yogyakarta, Indonesia',
  'Lombok, Indonesia',
  'Manila, Philippines',
  'Cebu, Philippines',
  'Palawan, Philippines',
  'Luang Prabang, Laos',
  'Siem Reap, Cambodia',
  'Phnom Penh, Cambodia',
  'Yangon, Myanmar',
  // Oceania
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Adelaide, Australia',
  'Cairns, Australia',
  'Gold Coast, Australia',
  'Uluru, Australia',
  'Queenstown, New Zealand',
  'Auckland, New Zealand',
  'Rotorua, New Zealand',
  'Wellington, New Zealand',
  'Fiji, Fiji',
  'Bora Bora, French Polynesia',
  'Tahiti, French Polynesia',
  // Russia & Central Asia (popular stops)
  'St. Petersburg, Russia',
  'Moscow, Russia',
  'Tbilisi, Georgia',
  'Yerevan, Armenia',
  'Baku, Azerbaijan',
  'Almaty, Kazakhstan',
  'Ulaanbaatar, Mongolia',
]

/** @type {readonly string[]} */
export const DESTINATION_OPTIONS = Array.from(
  new Set([...US_STATES, ...US_CITIES, ...INTERNATIONAL]),
)

export function filterDestinationOptions(query, limit = 10) {
  const q = query.trim().toLowerCase()
  if (!q) return []

  const scored = []
  for (const dest of DESTINATION_OPTIONS) {
    const lower = dest.toLowerCase()
    if (!lower.includes(q)) continue
    const idx = lower.indexOf(q)
    let rank = idx
    if (idx === 0) rank -= 2000
    else if (/[ ,]/.test(lower[idx - 1])) rank -= 1000
    scored.push({ dest, rank })
  }

  scored.sort((a, b) => a.rank - b.rank || a.dest.localeCompare(b.dest))
  return scored.slice(0, limit).map((s) => s.dest)
}
