/**
 * agent.js — TERMINAL (CLI) INTERFACE TO TRIPPY
 *
 * This is NOT the HTTP API. It runs in your terminal:
 * - Reads lines you type (stdin).
 * - Sends them to Gemini via LangChain (same brain as the API in trippyCore.js).
 * - Prints streaming text to the terminal (stdout).
 *
 * The web frontend does NOT use this file; it uses backend/server.js instead.
 */

// All `import` statements must stay at the top (ES modules rule in Node).

// dotenv loads environment variables from .env files into process.env (where GEMINI_API_KEY is read).
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";

// Node's readline lets us prompt "You: " and wait for keyboard input line by line.
import readline from "readline";

// HumanMessage = one user turn. AIMessage = one model turn. (System prompt is inside trippyCore.)
import { HumanMessage, AIMessage } from "@langchain/core/messages";

// Shared factory + helpers: one source of truth with the API.
import {
  initialMessageHistory, // Starting state: [system prompt].
  createTrippyLlm, // Builds ChatGoogle with your API key.
  chunkText, // Normalizes stream chunks to plain text.
} from "./trippyCore.js";

// import.meta.url is the absolute URL of *this* file; convert to a filesystem path.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Load backend/.env first so the same key file as the API works when you run `npm run agent` from the repo root.
dotenv.config({ path: path.join(__dirname, "../backend/.env") });
// Then load a .env in the current working directory if present (optional second source).
dotenv.config();

// Create ONE model client for the whole CLI session (reused each question).
// streaming: true ⇒ llm.stream(...) yields partial pieces as they arrive.
const llm = createTrippyLlm({ streaming: true });

// readline needs both input stream (keyboard) and output stream (terminal).
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

// Wraps rl.question in a Promise so we can use async/await in the loop below.
// resolve is called with whatever string the user typed when they press Enter.
const ask = (prompt) => new Promise((resolve) => rl.question(prompt, resolve));

// Conversation memory for Gemini: system message + every past user + assistant turn.
const messageHistory = initialMessageHistory();

// Initial greeting in the terminal (static copy; not generated by the model this turn).
console.log(
  "Trippy: Aloha! I'm Trippy, your personal travel curator. I'm already dreaming about your next getaway! To help me build the ultimate itinerary for you, tell me: where are we dreaming of going, and what's the one thing you can't travel without?\n",
);

// Infinite loop until user types "exit".
while (true) {
  // Wait for the user to type a line after the "You: " prompt.
  const userInput = await ask("You: ");

  // Graceful shutdown command (case-insensitive).
  if (userInput.toLowerCase() === "exit") {
    console.log(
      "\nTrippy: Safe travels! Come back anytime you're ready to plan your next adventure. ✈️",
    );
    break; // Exits the while loop.
  }

  // Skip empty lines without calling the API (saves quota and avoids useless requests).
  if (!userInput.trim()) continue;

  // Append latest user text to history BEFORE calling the model (model sees full thread).
  messageHistory.push(new HumanMessage(userInput));

  // Print assistant prefix without a trailing newline so streamed tokens appear on the same line.
  process.stdout.write("\nTrippy: ");

  // Ask Gemini for a streamed reply given every message in messageHistory.
  const stream = await llm.stream(messageHistory);
  let fullResponse = "";

  // Async iteration: each "chunk" is a piece of the answer as it arrives from Google.
  for await (const chunk of stream) {
    const text = chunkText(chunk);
    process.stdout.write(text); // Show token-by-token in terminal.
    fullResponse += text; // Accumulate full answer for history.
  }

  process.stdout.write("\n\n");

  // Store assistant reply so the NEXT user message has full context (multi-turn chat).
  messageHistory.push(new AIMessage(fullResponse));
}

// Close readline cleanly (releases stdin listener).
rl.close();
